# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 1009)
        MainWindow.setMinimumSize(QtCore.QSize(0, 900))
        MainWindow.setMaximumSize(QtCore.QSize(50000, 50000))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.treeView = QtWidgets.QTreeView(self.splitter)
        self.treeView.setMinimumSize(QtCore.QSize(0, 180))
        self.treeView.setMaximumSize(QtCore.QSize(256, 16777215))
        self.treeView.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"background-color: rgb(255, 255, 255);")
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.treeView.setDragDropOverwriteMode(True)
        self.treeView.setObjectName("treeView")
        self.Cell_Image = QtWidgets.QLabel(self.splitter)
        self.Cell_Image.setMinimumSize(QtCore.QSize(256, 256))
        self.Cell_Image.setMaximumSize(QtCore.QSize(256, 256))
        self.Cell_Image.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Cell_Image.setText("")
        self.Cell_Image.setObjectName("Cell_Image")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Datanumber = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Datanumber.setStyleSheet("font: 8pt \"Lucida Console\";\n"
"color: rgb(0, 0, 0);")
        self.Datanumber.setObjectName("Datanumber")
        self.horizontalLayout_7.addWidget(self.Datanumber)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.spinBox.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.spinBox.setMinimum(200)
        self.spinBox.setMaximum(10000)
        self.spinBox.setSingleStep(100)
        self.spinBox.setProperty("value", 500)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_7.addWidget(self.spinBox)
        self.Category_GroupBox = QtWidgets.QGroupBox(self.splitter)
        self.Category_GroupBox.setMinimumSize(QtCore.QSize(0, 200))
        self.Category_GroupBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Lucida Console\";")
        self.Category_GroupBox.setObjectName("Category_GroupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.Category_GroupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 231, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.Category_Layout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.Category_Layout.setContentsMargins(0, 0, 0, 0)
        self.Category_Layout.setObjectName("Category_Layout")
        self.Category_1 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Category_1.setStyleSheet("font: 14pt \"Lucida Console\";")
        self.Category_1.setObjectName("Category_1")
        self.Category_Layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Category_1)
        self.Category_box1 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.Category_box1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(65, 65, 65);")
        self.Category_box1.setObjectName("Category_box1")
        self.Category_Layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Category_box1)
        self.Category_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Category_2.setStyleSheet("font: 14pt \"Lucida Console\";")
        self.Category_2.setObjectName("Category_2")
        self.Category_Layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Category_2)
        self.Category_box2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.Category_box2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(65, 65, 65);")
        self.Category_box2.setObjectName("Category_box2")
        self.Category_Layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Category_box2)
        self.Gif = QtWidgets.QLabel(self.splitter)
        self.Gif.setMinimumSize(QtCore.QSize(256, 198))
        self.Gif.setText("")
        self.Gif.setObjectName("Gif")
        self.gridLayout.addWidget(self.splitter, 0, 0, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Lucida Console\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.System_Text = QtWidgets.QTextBrowser(self.splitter_2)
        self.System_Text.setMaximumSize(QtCore.QSize(16777215, 120))
        self.System_Text.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Lucida Console\";")
        self.System_Text.setObjectName("System_Text")
        self.label = QtWidgets.QLabel(self.splitter_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Lucida Console\";")
        self.label.setObjectName("label")
        self.System_textEdit = QtWidgets.QTextEdit(self.splitter_2)
        self.System_textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.System_textEdit.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Lucida Console\";")
        self.System_textEdit.setObjectName("System_textEdit")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter_2)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 500))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Log_layout = QtWidgets.QWidget()
        self.Log_layout.setObjectName("Log_layout")
        self.Log_Layout = QtWidgets.QHBoxLayout(self.Log_layout)
        self.Log_Layout.setObjectName("Log_Layout")
        self.Log_plot = QtWidgets.QLabel(self.Log_layout)
        self.Log_plot.setText("")
        self.Log_plot.setObjectName("Log_plot")
        self.Log_Layout.addWidget(self.Log_plot)
        self.tabWidget.addTab(self.Log_layout, "")
        self.tSNE_layout = QtWidgets.QWidget()
        self.tSNE_layout.setObjectName("tSNE_layout")
        self.tSNE_Layout = QtWidgets.QVBoxLayout(self.tSNE_layout)
        self.tSNE_Layout.setObjectName("tSNE_Layout")
        self.tabWidget.addTab(self.tSNE_layout, "")
        self.tSNE3D_layout = QtWidgets.QWidget()
        self.tSNE3D_layout.setObjectName("tSNE3D_layout")
        self.tSNE3D_Layout = QtWidgets.QVBoxLayout(self.tSNE3D_layout)
        self.tSNE3D_Layout.setObjectName("tSNE3D_Layout")
        self.tabWidget.addTab(self.tSNE3D_layout, "")
        self.gridLayout.addWidget(self.splitter_2, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(100, 100, 100);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 792, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.menuBar.setFont(font)
        self.menuBar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(150, 150, 150);")
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew_Model = QtWidgets.QMenu(self.menuFile)
        self.menuNew_Model.setObjectName("menuNew_Model")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFunction = QtWidgets.QMenu(self.menuBar)
        self.menuFunction.setObjectName("menuFunction")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuHelp_2 = QtWidgets.QMenu(self.menuBar)
        self.menuHelp_2.setObjectName("menuHelp_2")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_Model = QtWidgets.QAction(MainWindow)
        self.actionOpen_Model.setObjectName("actionOpen_Model")
        self.actionAddLabel = QtWidgets.QAction(MainWindow)
        self.actionAddLabel.setObjectName("actionAddLabel")
        self.actionSelect_Data_Path = QtWidgets.QAction(MainWindow)
        self.actionSelect_Data_Path.setObjectName("actionSelect_Data_Path")
        self.actionDel_Label = QtWidgets.QAction(MainWindow)
        self.actionDel_Label.setObjectName("actionDel_Label")
        self.actionUpdate_Setting = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Setting.setObjectName("actionUpdate_Setting")
        self.actionLoad_from_Data_Path = QtWidgets.QAction(MainWindow)
        self.actionLoad_from_Data_Path.setObjectName("actionLoad_from_Data_Path")
        self.actionStart_Training = QtWidgets.QAction(MainWindow)
        self.actionStart_Training.setObjectName("actionStart_Training")
        self.actionAutoencoder = QtWidgets.QAction(MainWindow)
        self.actionAutoencoder.setCheckable(True)
        self.actionAutoencoder.setChecked(True)
        self.actionAutoencoder.setObjectName("actionAutoencoder")
        self.actionAE_CS = QtWidgets.QAction(MainWindow)
        self.actionAE_CS.setCheckable(True)
        self.actionAE_CS.setObjectName("actionAE_CS")
        self.actionNo_Way = QtWidgets.QAction(MainWindow)
        self.actionNo_Way.setObjectName("actionNo_Way")
        self.actionStop_Training = QtWidgets.QAction(MainWindow)
        self.actionStop_Training.setObjectName("actionStop_Training")
        self.actionNew_tSNE = QtWidgets.QAction(MainWindow)
        self.actionNew_tSNE.setObjectName("actionNew_tSNE")
        self.menuNew_Model.addAction(self.actionAutoencoder)
        self.menuNew_Model.addAction(self.actionAE_CS)
        self.menuFile.addAction(self.menuNew_Model.menuAction())
        self.menuFile.addAction(self.actionOpen_Model)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSelect_Data_Path)
        self.menuFile.addAction(self.actionLoad_from_Data_Path)
        self.menuEdit.addAction(self.actionAddLabel)
        self.menuEdit.addAction(self.actionDel_Label)
        self.menuEdit.addAction(self.actionUpdate_Setting)
        self.menuFunction.addAction(self.actionStart_Training)
        self.menuFunction.addAction(self.actionStop_Training)
        self.menuFunction.addSeparator()
        self.menuFunction.addAction(self.actionNew_tSNE)
        self.menuHelp_2.addAction(self.actionNo_Way)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuFunction.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuBar.addAction(self.menuHelp_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Neuron Network Cell APP"))
        MainWindow.setStatusTip(_translate("MainWindow", "Ready"))
        self.Datanumber.setText(_translate("MainWindow", "Data Numbers/Label :"))
        self.Category_GroupBox.setTitle(_translate("MainWindow", "Category Setting"))
        self.Category_1.setText(_translate("MainWindow", "Label 1 :"))
        self.Category_2.setText(_translate("MainWindow", "Label 2 :"))
        self.label_2.setText(_translate("MainWindow", "Instruction"))
        self.System_Text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Console\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; color:#000000;\">Step 1: File/Select Data Path <br />Step 2: Label/Setup the Category Setting and update it <br />Step 3: File/Load the Data from Data Path<br />Step 4: File/Chose the Model you like<br />Step 5: Function/Start Training</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "System Information"))
        self.System_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Console\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Log_layout), _translate("MainWindow", "Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tSNE_layout), _translate("MainWindow", "tSNE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tSNE3D_layout), _translate("MainWindow", "tSNE3D"))
        self.label_5.setText(_translate("MainWindow", "Data Loaded"))
        self.label_3.setText(_translate("MainWindow", "Label Designed"))
        self.label_7.setText(_translate("MainWindow", "Training"))
        self.statusbar.setStatusTip(_translate("MainWindow", "Ready"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuNew_Model.setTitle(_translate("MainWindow", "Models"))
        self.menuEdit.setTitle(_translate("MainWindow", "Label"))
        self.menuFunction.setTitle(_translate("MainWindow", "Function"))
        self.menuHelp.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp_2.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen_Model.setText(_translate("MainWindow", "Open Model"))
        self.actionAddLabel.setText(_translate("MainWindow", "Add Label"))
        self.actionSelect_Data_Path.setText(_translate("MainWindow", "Select Data Path"))
        self.actionSelect_Data_Path.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionDel_Label.setText(_translate("MainWindow", "Del Label"))
        self.actionUpdate_Setting.setText(_translate("MainWindow", "Update"))
        self.actionUpdate_Setting.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionLoad_from_Data_Path.setText(_translate("MainWindow", "Load from Data Path"))
        self.actionLoad_from_Data_Path.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionStart_Training.setText(_translate("MainWindow", "Start Training"))
        self.actionStart_Training.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionAutoencoder.setText(_translate("MainWindow", "Autoencoder(AE)"))
        self.actionAE_CS.setText(_translate("MainWindow", "AE+CS"))
        self.actionNo_Way.setText(_translate("MainWindow", "No Way"))
        self.actionStop_Training.setText(_translate("MainWindow", "Stop Training"))
        self.actionNew_tSNE.setText(_translate("MainWindow", "New tSNE"))
        self.actionNew_tSNE.setShortcut(_translate("MainWindow", "Ctrl+N"))

